CREATE DATABASE escola;
USE DATABASE escola;

CREATE TABLE alunos {
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(64),
    IDADE INT,
    NOTA FLOAT
};

CREATE TABLE professores {
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(64),
    DISCIPLINA VARCHAR(64),
    SALARIO INT
};

CREATE TABLE materias {
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(64),
    ID_PROFESSOR VARCHAR(64),
    DURACAO_SEG INT
};

CREATE TRIGGER verifica_nota
  BEFORE INSERT ON alunos
  FOR EACH ROW
BEGIN
  IF NEW.nota < 7 THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Nota inválida';
  END IF;
END;

